### ISSUE TITLE
Creación de usuarios administrativos

### ISSUE THREAD

**Issue by gaos180** [gaos180/denuncias#29]
Historia de usuario:
Yo como parte del staff, siendo un usuario administrativo, quiero poder crear una cuenta para ingresar a la plataforma de administrar las denuncias

Prioridad:

Dependencias:

Prueba de aceptación:

**Comment by ghost** [comment]
Error. No completada.

**Comment by gaos180** [comment]
completada con el paso de commits, se crean primero el usuario y luego se le cambia el estado
