### ISSUE TITLE
Ingreso usuarios administrativos

### ISSUE THREAD

**Issue by gaos180** [gaos180/denuncias#30]
Historia de usuario:
Yo como parte del staff, siendo un usuario administrativo, quiero poder ingresar a una cuenta ya creada de administrador.

Prioridad:

Dependencias: Creación de usuarios administrativos

Prueba de aceptación:

**Comment by ghost** [comment]
Error. Tarea no completada.

**Comment by gaos180** [comment]
La tarea ha sido completada con el paso de los commits
